server:
  port: 7090
  servlet:
    context-path: /api
    session:
      timeout: PT60M
#数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password:
    url: jdbc:mysql://localhost/wohayp?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
  task:
    execution:
      thread-name-prefix: async-executor- # 异步任务执行的线程名称前缀
      pool:
        core-size: 10 # 线程池的核心线程数
        max-size: 20 # 线程池的最大线程数
        queue-capacity: 1000 # 任务队列的容量
  #qq邮箱验证码
  mail:
    host: smtp.qq.com  # 配置 smtp 服务器地址
    port: 587  # smtp 服务器端口
    username:  #配置你的邮箱地址
    password:  #配置申请到的授权码
    protocol: smtp
    defaultEncoding: utf-8
  #redis
  redis:
    host: localhost
    port:
    password:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    jackson:
      default-property-inclusion: non_null # JSON处理时忽略非空字段
#文件上传
  servlet:
    multipart:
      max-file-size: 15MB
      maxRequestSize: 30MB
mybatis-plus:
  type-aliases-package: com.starQeem.wohayp.pojo
#logging:
#  level:
#    com:
#      starQeem:
#        wohayp: debug  #开启日志


